/**
 * Below are the Constants that are used in the app.
 */

const webUrl = 'https://lahelu.com';
const apiUrl = 'https://lahelu.com/api';
const postUrl = 'https://lahelu.com/post';

export const Constants = {
  webUrl,
  apiUrl,
  postUrl,
  tags: [
    ['Lucu', `${webUrl}/media/hashtags/funny.jpg`],
    ['Relate', `${webUrl}/media/hashtags/relate.jpg`],
    ['Gaming', `${webUrl}/media/hashtags/gaming.jpg`],
    ['Nostalgia', `${webUrl}/media/hashtags/nostalgia.jpg`],
    ['Sad', `${webUrl}/media/hashtags/sad.jpg`],
    ['Random', `${webUrl}/media/hashtags/random.jpg`],
    ['Wtf', `${webUrl}/media/hashtags/wtf.jpg`],
    ['Rage', `${webUrl}/media/hashtags/rage.jpg`],
    ['Anime', `${webUrl}/media/hashtags/anime.jpg`],
    ['Sarkas', `${webUrl}/media/hashtags/sarcastic.jpg`],
    ['Dark', `${webUrl}/media/hashtags/dark.jpg`],
    ['Absurd', `${webUrl}/media/hashtags/absurd.jpg`],
    ['Cringe', `${webUrl}/media/hashtags/cringe.jpg`],
    ['Sus', `${webUrl}/media/hashtags/sus.jpg`],
    ['Binatang', `${webUrl}/media/hashtags/animal.jpg`],
  ],
  headerHeight: 49,
  tabHeight: 39,
  drawerHeaderHeight: 57,
  imageHeightLahelu: 25, // BASED ON THE IMAGE RATIO
  imageWidthLahelu: 94, // BASED ON THE IMAGE RATIO
  imageWidthLaheluIcon: 50,
  imageWidthAvatar: 30,
  imageWidthTagSmall: 24,
  postHeaderHeight: 30,
  postSeparatorHeight: 4,
  postPillHeight: 24,
  postBoxHeight: 38,
  postPlayHeight: 50,
  postDurationBottom: 28,
  postSliderHeight: 4,
  postSliderThumbHeight: 16,
  textXS: 10,
  textSM: 12,
  textMD: 14,
  textLG: 16,
  textXL: 18,
  textXL2: 20,
  textXL3: 22,
  lineHeightXS: 24,
  lineHeightSM: 30,
  lineHeightMD: 50,
  lineHeightLG: 60,
  inputHeightSM: 36,
  inputHeightMD: 40,
  inputHeightLG: 46,
  inputHeightXL: 50,
  buttonWidthXS: 30,
  buttonWidthXS2: 40,
  buttonWidthSM: 80,
  buttonWidthSM2: 100,
  buttonWidthMD: 120,
  buttonWidthMD2: 140,
  buttonWidthLG: 160,
  buttonWidthLG2: 180,
  buttonWidthXL: 200,
  buttonWidthXL2: 220,
  buttonHeightSM: 30,
  buttonHeightMD: 40,
  buttonHeightLG: 60,
  buttonHeightXL: 80,
  iconXS: 14,
  iconSM: 18,
  iconSM2: 20,
  iconMD: 22,
  iconMD2: 24,
  iconLG: 28,
  iconLG2: 32,
  iconXL: 36,
  iconXL2: 42,
  borderRadiusXS: 2,
  borderRadiusSM: 4,
  borderRadiusMD: 8,
  borderRadiusLG: 12,
  borderRadiusCircle: 50,
  borderRadiusMax: 999,
  spacingXS: 1,
  spacingXS2: 2,
  spacingXS3: 4,
  spacingXS4: 6,
  spacingSM: 8,
  spacingSM2: 10,
  spacingSM3: 12,
  spacingMD: 14,
  spacingMD2: 16,
  spacingMD3: 18,
  spacingLG: 20,
  spacingLG2: 22,
  spacingLG3: 24,
};
